### PR TITLE
Make attestation cert available

### PR DESCRIPTION
**Pull request by larsonmpdx**
lets the calling application retrieve the attestation cert, same style as retrieving the keyhandle/publickey

### CODE REVIEW

**Comment by a-dma** [comment]
I'm wondering if it's better to do a i2d on the cert and return it as an array of bytes rather than a void *.

We should also export the new function in  the map file and bump the libtool version, but I can help with that.

**Comment by larsonmpdx** [comment]
yeah, it would be fair to include some processing inside the library.  would PEM be ok?  that would meet my needs (record keeping in an ASCII format) and I think most people will be wanting something similar for record keeping vs. online verification

**Comment by a-dma** [comment]
PEM would definitely be ok, it also ties nicely into #7 making that part pretty much trivial.

**Comment by larsonmpdx** [comment]
this is ready, works fine

**Comment by a-dma** [comment]
Why store the PEM encoded cert directly into `u2fs_reg_res` alongside with the binary version? Am I missing something?

To me it makes more sense to call `dump_` from inside `u2fs_get_` and copy the result to a user-provided buffer or a newly allocated one if a buffer is not provided.

**Comment by larsonmpdx** [comment]
That might make more sense.  I was trying to maintain the existing style of the codebase: the user public key is already stored as both an openssl ec point (u2fs_EC_KEY_t *user_public_key) and an octet string ec point (char *publicKey), and the work to create the duplicate copy is in u2fs_get_authentication_result().  I decided to mirror this arrangement

**Comment by a-dma** [comment]
You're right.
That doesn't seem like a clever thing to do. I'll have to look into it. Thanks.

**Comment by a-dma** [comment]
I've pushed some code to get rid of the extra public key. If you're going to update the PR I'll get it in.

**Comment by a-dma** [comment]
Hi, any update on rebasing this PR or should I go on and take ownership?

**Comment by thorduri** [comment]
I've updated this PR in #25 with some rebases and fixups.

Thanks @larsonmpdx !

**Pull request closed without merging**
